Repository GEOS-ESM/GEOSchem_GridComp, pull requests merged in 2021-05, with the labels that each got.

#122 Bring in Optics f2py update
  MAMchem_GridComp/CMakeLists.txt
  MAMchem_GridComp/optics/CMakeLists.txt
Labels: 0 diff

#129 Update CircleCI to use xlarge
  .circleci/config.yml
Labels: 0 diff trivial

#121 Update bundleParser.py to be Python agnostic
  Shared/Chem_Shared/bundleParser.py
Labels: 0 diff

#123 Updates to use Python2 and Python3 at same time
  .circleci/config.yml
  Shared/Chem_Base/CMakeLists.txt
Labels: 0 diff

#127 Add CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#131 Fixes for F2PY using GNU
  MAMchem_GridComp/optics/mie.F90
Labels: 0 diff, 0 diff trivial

#132 Made RI and RL imports conditional on running Cloud-J
  GMIchem_GridComp/GMI_GridComp/GMI_Registry.rc
  GMIchem_GridComp/GMI_GridComp/GmiPhotolysis_GridCompClassMod.F90
  GMIchem_GridComp/GMIchem_GridCompMod.F90
Labels: 0 diff
