Repository GEOS-ESM/GEOSchem_GridComp, pull requests merged in 2022-08, with the labels that each got.

#204 Closes #203. Add QuickChem repo to gitignore
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
Labels: 0 diff trivial

#205 Handmerge main into develop 2022-Aug-04
  .gitignore
  CHANGELOG.md
Labels: 0 diff trivial

#206 GMI now uses CMIP6 emissions
  CHANGELOG.md
  ChemEnv_ExtData.rc
  ChemEnv_ExtData.yaml
  GMIchem_GridComp/GMI_GridComp/GMI_ExtData.rc
  GMIchem_GridComp/GMI_GridComp/GMI_ExtData.yaml
  GMIchem_GridComp/GMI_GridComp/GMI_GridComp.rc
  HEMCO_GridComp/HEMCOgmi_ExtData.rc
  HEMCO_GridComp/HEMCOgmi_ExtData.yaml
Labels: 0 diff

#207 incremental improvements to GMI
  CHANGELOG.md
  GEOS_ChemEnvGridComp.F90
  GMIchem_GridComp/GMI_GridComp/GMI_GridComp.rc
  GMIchem_GridComp/GMI_GridComp/GmiSAD_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiSwapSpeciesBundlesMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiThermalRC_GridCompClassMod.F90
Labels: 0 diff

#208 merge CHEM develop into main, 8-16-22
  .github/workflows/changelog-enforcer.yml
  .github/workflows/validate_yaml_files.yml
  .yamllint.yml
  CHANGELOG.md
  ChemEnv_ExtData.rc
  ChemEnv_ExtData.yaml
  GEOSCHEMchem_GridComp/CMakeLists.txt
  GEOS_ChemEnvGridComp.F90
  GMIchem_GridComp/GMI_GridComp/GMI_ExtData.rc
  GMIchem_GridComp/GMI_GridComp/GMI_ExtData.yaml
  GMIchem_GridComp/GMI_GridComp/GMI_GridComp.rc
  GMIchem_GridComp/GMI_GridComp/GMI_Registry.rc
  GMIchem_GridComp/GMI_GridComp/GmiChemistry/GmiPhotolysisRateConstants_mod.F90
  GMIchem_GridComp/GMI_GridComp/GmiDepos_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiDeposition/GmiDepositionMethod_mod.F90
  GMIchem_GridComp/GMI_GridComp/GmiDeposition/drydep_update.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmiss_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/GmiEmissionMethod_mod.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/emiss_update.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/harvard/GmiSoilEmission_mod.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/harvard/emiss_harvard.F90
  GMIchem_GridComp/GMI_GridComp/GmiPhotolysis_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiSAD_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiShared/GmiSupportingModules/GmiResistance_mod.F90
  GMIchem_GridComp/GMI_GridComp/GmiSwapSpeciesBundlesMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiThermalRC_GridCompClassMod.F90
  GMIchem_GridComp/GMIchem_GridCompMod.F90
  HEMCO_GridComp/HEMCOgmi_ExtData.rc
  HEMCO_GridComp/HEMCOgmi_ExtData.yaml
  TR_GridComp/DryDepositionGmiMod.F90
  TR_GridComp/TR_GridCompMod.F90
Labels: 0 diff

#210 fixes #209
  CHANGELOG.md
  ChemEnv_ExtData.yaml
  GAAS_GridComp/GAAS_GridComp_ExtData.yaml
Labels: 0 diff, bugfix

#211 GMI random cloud overlap
  CHANGELOG.md
  GMIchem_GridComp/GMI_GridComp/GmiEmiss_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/harvard/emiss_harvard.F90
  GMIchem_GridComp/GMI_GridComp/GmiPhotolysis_GridCompClassMod.F90
  GMIchem_GridComp/GMIchem_GridCompMod.F90
Labels: 0 diff

#212 new Runtime_Registry
  CHANGELOG.md
  GEOS_ChemGridComp.F90
  Shared/Chem_Base/CMakeLists.txt
  Shared/Chem_Base/Runtime_RegistryMod.F90
  TR_GridComp/TR_ExtData.rc
  TR_GridComp/TR_ExtData.yaml
  TR_GridComp/TR_GridCompMod.F90
  TR_GridComp/TR_Registry.rc
Labels: 0 diff

#213 Delete the parts of Chem_Registry related to TR, now handled separately
  CHANGELOG.md
  Shared/Chem_Base/AMIP/Chem_Registry.rc
  Shared/Chem_Base/Chem_Registry.rc
  Shared/Chem_Base/Chem_RegistryMod.F90
Labels: 0 diff

#214 New TR Registry; GMI photolysis update
  CHANGELOG.md
  ChemEnv_ExtData.yaml
  GAAS_GridComp/GAAS_GridComp_ExtData.yaml
  GEOS_ChemGridComp.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmiss_GridCompClassMod.F90
  GMIchem_GridComp/GMI_GridComp/GmiEmission/harvard/emiss_harvard.F90
  GMIchem_GridComp/GMI_GridComp/GmiPhotolysis_GridCompClassMod.F90
  GMIchem_GridComp/GMIchem_GridCompMod.F90
  Shared/Chem_Base/AMIP/Chem_Registry.rc
  Shared/Chem_Base/CMakeLists.txt
  Shared/Chem_Base/Chem_Registry.rc
  Shared/Chem_Base/Chem_RegistryMod.F90
  Shared/Chem_Base/Runtime_RegistryMod.F90
  TR_GridComp/TR_ExtData.rc
  TR_GridComp/TR_ExtData.yaml
  TR_GridComp/TR_GridCompMod.F90
  TR_GridComp/TR_Registry.rc
Labels: 0 diff
